### ISSUE TITLE
Android Tensorflow Lite : Unable to Convert from Tensorflow Lite Buffer 

### ISSUE THREAD

**Issue by hbsuhas** [KinarR/age-gender-estimator-keras#3]
Hello,

After exporting to android . The *.tflite model is not loading and its throwing error saying 
unable to convert Tensorflow lite buffer to ByteBuffer:
Error : java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with xxxx bytes and a ByteBuffer with xxxx bytes.
at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:251)
at org.tensorflow.lite.Tensor.setTo(Tensor.java:110)
at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:145)
at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)

**Comment by KinarR** [comment]
I believe you are trying to load it as a quantized model which would have a buffer size of exactly 4 times smaller. Make sure to use the [ImageClassifierFloatMobileNet](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifierFloatMobileNet.java) class in the [TFLite Standalone Image Classifier](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo) example and place your model in the assets directory.

**Comment by KinarR** [comment]
Also if you're attempting to modify this (example)[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/android/app/src/main/java/org/tensorflow/demo/TFLiteImageClassifier.java],  in the method **convertBitmapToByteBuffer** you'd need 4 bytes for each value since the datatype for inputs and outputs of the exported model is float.

Replace
`ByteBuffer byteBuffer = ByteBuffer.allocateDirect(BATCH_SIZE * inputSize * inputSize * PIXEL_SIZE);
`
with
`ByteBuffer byteBuffer = ByteBuffer.allocateDirect(4 * BATCH_SIZE * inputSize * inputSize * PIXEL_SIZE);
`
Also, swap `byteBuffer.put` with `byteBuffer.putFloat`.

**Comment by hbsuhas** [comment]
Thank you KinarR    i am able to load the tflite model and able to see the result.
as of now i am getting single output prediction.

**Comment by KinarR** [comment]
Ah, right. In order to get multiple outputs, use the **runForMultipleInputsOutputs** method on the TFLite interpreter instance as follows

outputGender= new float[1][NUM_DETECTIONS];
outputAge = new float[1][NUM_DETECTIONS];

Object[] inputArray = {imgData};
Map<Integer, Object> outputMap = new HashMap<>();

outputMap.put(0, outputGender);
outputMap.put(1, outputAge);

// Run the inference call.
tfLite.runForMultipleInputsOutputs(inputArray, outputMap);

**Comment by hbsuhas** [comment]
Hi KinarR,
Thank you for Guiding me. I am able to apply the above code.
and i am getting Below values. 

D/TfLiteCameraDemo: Timecost to run model inference: 325
D/Age Get: Age Index is 1
**D/OutPut age Get: Age is 0.0044081328
D/At applyFIlter: Age is 0.0044081328**

in python It was easy to transform those values to real AGE.
 
Python Code
                  ```
                       ages = np.arange(0, 21).reshape(21, 1)
                       predicted_age = results[1].dot(ages).flatten()
                       print(predicted_age[0]*4.76) 
```
Can you please help me to transform them to numbers ?

**Comment by hbsuhas** [comment]
Hello KinarR
I am able to get the values in android similar to Python.
Thank you for your help. :)

**Comment by KinarR** [comment]
Glad to help! Thank you checking out my repo.

**Comment by KinarR** [comment]
Glad to help! Thank you for checking out my repo.

**Comment by vhghorecha** [comment]
@hbsuhas can you share your Android version with me?
